# Generated by Django 5.1.1 on 2024-09-30 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.BooleanField()),
                ('department', models.BooleanField()),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shared.client')),
            ],
        ),
    ]
