# Generated by Django 5.1.1 on 2024-09-30 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0002_feature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='department',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='feature',
            name='employee',
            field=models.BooleanField(default=False),
        ),
    ]
